package com.job.utils


import com.job.model.Ambiente;
import java.util.concurrent.TimeUnit;

rule "Ligar ArCondicionado"	

when
a : Ambiente (qntPessoas > 3)
then

TimeUnit.MINUTES.sleep(10);
System.out.println("Ambiente quantidade de Pessoas:" + a.getQntPessoas() + " Ar-Condicionado é ligado");

end;

rule "Acender Lampada"

when
a : Ambiente (qntPessoas > 0,  distancia == 0)
then
TimeUnit.SECONDS.sleep(4);
a.setPotenciaLampada(100);
System.out.println("Ambiente quantidade de Pessoas:" + a.getQntPessoas() + " potência da Lampada:" + a.getPotenciaLampada()+"%");
end;

rule "Desligar Lampada"	

when
a : Ambiente (qntPessoas == 0)
then
a.setPotenciaLampada(0);
System.out.println("Ambiente quantidade de Pessoas:" + a.getQntPessoas() + " potência da Lampada:" + a.getPotenciaLampada()+"%");
end;

rule "Acender Lampada de acordo com a distancia"	

when
a : Ambiente (qntPessoas > 0, distancia > 1)
then

TimeUnit.SECONDS.sleep(2);
a.setPotenciaLampada(25);
System.out.println("Ambiente quantidade de Pessoas:" + a.getQntPessoas() + " potência da Lampada:" + a.getPotenciaLampada()+"%");
TimeUnit.SECONDS.sleep(1);
a.setPotenciaLampada(50);
System.out.println("Ambiente quantidade de Pessoas:" + a.getQntPessoas() + " potência da Lampada:" + a.getPotenciaLampada()+"%");
TimeUnit.SECONDS.sleep(1);
a.setPotenciaLampada(75);
System.out.println("Ambiente quantidade de Pessoas:" + a.getQntPessoas() + " potência da Lampada:" + a.getPotenciaLampada()+"%");
TimeUnit.SECONDS.sleep(1);
a.setPotenciaLampada(100);
System.out.println("Ambiente quantidade de Pessoas:" + a.getQntPessoas() + " potência da Lampada:" + a.getPotenciaLampada()+"%");
end;
